version: "3"

services:
  volar:
    image: volar
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: "${NODE_ENV}"
      APP_ENV: "${APP_ENV}"
      CLIENT_URI: "${CLIENT_URI}"
      SERVER_URI: "${SERVER_URI}"
      DATABASE_CONNECTION_STRING: "${DATABASE_CONNECTION_STRING}"
      APP_LOG: "${APP_LOG}"
    ports:
      - 80:3000
    restart: always
    volumes:
      - "${LOG_BASE_DIR}/volar:/var/log/volar"
